// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJD5kMrwaSo0cp3T5GmPSqGKSjBxKF9s',
    appId: '1:403568295880:web:3d80110ea0f8f11c154afd',
    messagingSenderId: '403568295880',
    projectId: 'contentmanagementapp-398e3',
    authDomain: 'contentmanagementapp-398e3.firebaseapp.com',
    storageBucket: 'contentmanagementapp-398e3.firebasestorage.app',
    measurementId: 'G-WW7E0QZ5QV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqKsc4e-omztAO_QGINKSZ5ds0_tPJrMo',
    appId: '1:403568295880:android:be872a2e5d554fbf154afd',
    messagingSenderId: '403568295880',
    projectId: 'contentmanagementapp-398e3',
    storageBucket: 'contentmanagementapp-398e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPUZ-SeHs7Xr1UP-FJtx_n0yqDUpaqfAo',
    appId: '1:403568295880:ios:0671e8501d92c3a7154afd',
    messagingSenderId: '403568295880',
    projectId: 'contentmanagementapp-398e3',
    storageBucket: 'contentmanagementapp-398e3.firebasestorage.app',
    iosBundleId: 'com.example.contentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPUZ-SeHs7Xr1UP-FJtx_n0yqDUpaqfAo',
    appId: '1:403568295880:ios:0671e8501d92c3a7154afd',
    messagingSenderId: '403568295880',
    projectId: 'contentmanagementapp-398e3',
    storageBucket: 'contentmanagementapp-398e3.firebasestorage.app',
    iosBundleId: 'com.example.contentManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdJD5kMrwaSo0cp3T5GmPSqGKSjBxKF9s',
    appId: '1:403568295880:web:ca4238182ef66811154afd',
    messagingSenderId: '403568295880',
    projectId: 'contentmanagementapp-398e3',
    authDomain: 'contentmanagementapp-398e3.firebaseapp.com',
    storageBucket: 'contentmanagementapp-398e3.firebasestorage.app',
    measurementId: 'G-2Z9KRRF91M',
  );

}